/** Settings keys aligned with backend CANONICAL_SETTINGS_KEYS */

export const SETTINGS_KEYS = [
  'TELEMETRY_BACKEND',
  'SERIAL_PORT',
  'SERIAL_BAUD',
  'LOCAL_LLM_PROVIDER',
  'LOCAL_LLM_BASE_URL',
  'LOCAL_LLM_MODEL',
  'LOCAL_LLM_TIMEOUT',
  'OLLAMA_NUM_THREAD',
  'AI_HAT_ENABLED',
  'AI_HAT_REQUIRE_HARDWARE',
  'AI_HAT_CAMERA_PIPELINE_ENABLED',
  'AI_HAT_OBJECT_DETECTION_ENABLED',
  'AI_HAT_DETECTION_THRESHOLD',
  'AIRAUTOMATICA_PREPROCESSING_ENABLED',
  'AI_MIN_CONFIDENCE',
  'AI_DUPLICATE_WINDOW_SEC',
  'AI_SCHEDULER_COOLDOWN_SEC',
  'CAMERA_RECORDING_MODE',
  'RECORDING_AI_OVERLAY_ENABLED',
  'RECORDING_AI_PERSIST_ENABLED',
  'SESSION_AUTO_START_ON_ARM',
] as const

export const CHECKBOX_KEYS = new Set([
  'AI_HAT_ENABLED',
  'AI_HAT_REQUIRE_HARDWARE',
  'AI_HAT_CAMERA_PIPELINE_ENABLED',
  'AI_HAT_OBJECT_DETECTION_ENABLED',
  'AIRAUTOMATICA_PREPROCESSING_ENABLED',
  'RECORDING_AI_OVERLAY_ENABLED',
  'RECORDING_AI_PERSIST_ENABLED',
  'SESSION_AUTO_START_ON_ARM',
])
